[package]
name = "cstea"
version = "0.1.0"
authors = ["Benjamin Slater <benjamin.ed.slater@gmail.com>"]
edition = "2018"

[dependencies]
rettle = { git = "ssh://git@github.com/slaterb1/rettle" }
csv = "1"
